services:
  stardew:
    restart: unless-stopped
    container_name: stardew-server
    # Remember to have the game files in .tar.gz format present.
    # If you want another file format, change it accordingly.
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3001:3001/tcp"
      - "24642:24642/udp"
    volumes:
      - ./config:/config/modconfs
      - ./save_games:/config/.config/StardewValley/Saves
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]
