services:
  stardew:
    restart: unless-stopped
    container_name: stardew-server
    image: stardew-server:latest
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
    ports:
      - "3001:3001/tcp"
      - "24642:24642/udp"
    volumes:
      - ./config:/config
      - ./save_games:/config/.config/StardewValley/Saves
