name: Docker Scan and Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_IMAGE: dselen/stardew-server
  GAMEFILE_NAME: latest.tar.gz

jobs:
  docker_build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create dummy Stardew Valley file
        run: |
          mkdir Stardew\ Valley
          touch Stardew\ Valley/dummy.bogus
          tar -czvf ./${{ env.GAMEFILE_NAME }} ./Stardew\ Valley

      - name: Build and export (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
          tags: ${{ env.DOCKER_IMAGE }}:latest
          platforms: linux/amd64

      #- name: Docker Scout
      #  id: docker-scout
      #  uses: docker/scout-action@v1
      #  with:
      #    command: cves
      #    dockerhub-user: ${{ secrets.DOCKER_HUB_USERNAME }}
      #    dockerhub-password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      #    image: ${{ env.DOCKER_IMAGE }}:latest
      #    only-severities: critical,high,medium,low,unspecified
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
