name: Test Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_IMAGE: dselen/stardew-server
  GAMEFILE_NAME: latest.tar.gz

jobs:
  build_scan_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create dummy Stardew Valley file and cleanup
        run: |
          mkdir Stardew\ Valley
          touch Stardew\ Valley/dummy.bogus
          tar -czvf ./${{ env.GAMEFILE_NAME }} ./Stardew\ Valley
          rm -rf Stardew\ Valley

      - name: Build and export (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
          tags: ${{ env.DOCKER_IMAGE }}:latest
          platforms: linux/amd64

      - name: Docker Scout
        id: docker-scout
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/scout-action@dd36f5b0295baffa006aa6623371f226cc03e506
        with:
          command: quickview, cves
          image: local://${{ env.DOCKER_IMAGE }}:latest
          ignore-unchanged: true
          only-severities: critical,high
          github-token: ${{ secrets.GITHUB_TOKEN }}
